ALTER TABLE sync_state ADD COLUMN uid_validity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_state ADD COLUMN last_uid INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_state ADD COLUMN auth_method TEXT NOT NULL DEFAULT 'oauth';
